# Generated by Django 3.2.5 on 2021-07-28 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_golfapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Game', to='card_golfapi.round'),
        ),
        migrations.AlterField(
            model_name='round',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Round', to='card_golfapi.game'),
        ),
    ]
