# Generated by Django 3.2.5 on 2021-07-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_golfapi', '0002_auto_20210728_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
